
[profile.default]
solc_version = '0.8.20'
evm_version = 'shanghai'
auto_detect_solc = false
optimizer = true
optimizer_runs = 200 # Default amount
ffi = true
fuzz_runs = 1_000

fs_permissions = [
    { access = "read", path = "./src/test/Polynomial.t.huff" },
    { access = "read", path = "./src/test/Huffd1.t.huff" }
]
